version: '3.8'
services:
  setup:
    build: .
    command: ["sh", "-c", "npm run setup && echo 'SETUP_COMPLETE_MARKER' && touch /app/database/.setup_done"]
    volumes:
      - ./database:/app/database
      - ./data_model:/app/data_model
    environment:
      - NODE_ENV=production
    restart: "no"

  app:
    build: .
    depends_on:
      setup:
        condition: service_completed_successfully
    ports:
      - "3000:3000"
    volumes:
      - ./database:/app/database
      - ./data_model:/app/data_model
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
    entrypoint: ["sh", "./wait-for-setup.sh", "node", "server.js"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
